<?php
/**
 * Adjustments to default WordPress handling of styles.
 *
 * @package jeremyfelt
 */

namespace JeremyFelt\WP\Styles;

add_action( 'plugins_loaded', __NAMESPACE__ . '\remove_global_styles' );

/**
 * Remove the global styles generated by WordPress and Gutenberg on
 * the front end for the block editor.
 */
function remove_global_styles() {
	remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
	remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );

	remove_action( 'wp_enqueue_scripts', 'wp_enqueue_global_styles' );
	remove_action( 'wp_enqueue_scripts', 'gutenberg_enqueue_global_styles' );

	remove_action( 'wp_enqueue_scripts', 'wp_common_block_scripts_and_styles' );

	remove_action( 'wp_footer', 'gutenberg_enqueue_global_styles', 1 );

	// WordPress 6.1 injects a new stylesheet for classic themes.
	remove_action( 'wp_enqueue_scripts', 'wp_enqueue_classic_theme_styles' );
	remove_action( 'admin_enqueue_scripts', 'wp_enqueue_classic_theme_styles' );
}
