# If XDebug is enabled, disable it
xdebug_off() {
	sudo php5dismod xdebug
	sudo service php5-fpm restart
}

# If XDebug is disabled, enable it
xdebug_on() {
	sudo php5enmod xdebug
	sudo service php5-fpm restart
}
